### ISSUE TITLE
refactor parse_shows()

### ISSUE THREAD

**Issue by aqw** [pigskin/pigskin#13]
Multiple functions need to be refactored here:

- [x] parse_shows()
- [x] get_shows()
- [ ] get_shows_episodes()

I suggest that the information delivered by the API be inverted here. Right now, we are assuming that the consumer of the API wants to know all the seasons before getting into a show. The Game Pass website has the user select a show first before getting into the season/episodes. I think this is sane --- and certainly far more efficient.

This will cause serious UI breakage for xbmc-gamepass, and thus IMO, should happen as part of the new API being planned (#15).

**Comment by aqw** [comment]
Part of #15

**Comment by jm-duke** [comment]
Closing this issue, as NFL has canceled the Gamepass service
