### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by aqw** [pigskin/pigskin#15]
This will be edited to remain up-to-date with the the proposed API as it evolves.

The new API will take a much more OOP approach, and use context to save the user from the hassle of slinging values around all the time.

The information should be acquired on-demand, with caching (that can be overridden). Some information (such as seasons) should never expire, whereas game information should have a relatively short (say 5 minutes) TTL.

# API

## Games
- [X] ``gp.seasons`` - type OrderedDict of Season objects
     ```
    >>> type(gp.seasons['2016'])
    pigskin.season
    ```
- [X] ``gp.seasons['2016']`` - type season
- [X] ``gp.seasons['2017'].weeks`` - type OrderedDict of season-types containing OrderedDicts of weeks with their corresponding Week object.
    ````
    >>> type(gp.seasons['2017'].weeks['pre']['0'])
    'pigskin.week'
    >>> print(gp.seasons['2017'].weeks['pre']['0'].desc)
    'Hall of Fame'
    >>> print(gp.seasons['2017'].weeks['reg']['8'].desc)
    ''
    >>> print(gp.seasons['2017'].weeks['post']['22'].desc)
    'Super Bowl'
    ````
- [X] ``gp.seasons['2017'].weeks['pre']['0']`` type week
- [X] ``gp.season['2017']['reg'].week['8'].games`` - type OrderedDict of game objects.
- [X] ``gp.season['2017']['reg'].week['8'].games['Bears@Packers']`` - type game.
    - Has tons of metadata. Will write about it in docs
- [X] ``gp.season['2017']['reg'].week['8'].games['Bears@Packers'].versions`` - type OrderedDict of version objects.
    - List the versions available (full, condensed, coaches)
- [X] ``gp.season['2017']['reg'].week['8'].games['Bears@Packers'].versions['full']`` - type version
- [X] ``gp.season['2017']['reg'].week['8'].games['Bears@Packers'].versions['full'].streams`` - type dict
    - List the streams available (hls, chromecast, etc) and their content URL.
- [ ] ``gp.season['2017']['reg'].week['8'].games['Bears@Packers'].versions['full'].streams['hls']`` - type stream
    - Perhaps this is where ``m3u8_to_dict`` belongs
- [X] ``gp.season['2017'].teams`` - type OrderedDict of team objects
    - This is under ``season`` because teams do move :-/
    - TODO: I'm not sure if Game Pass Europe provides info for anything other than the current season, which could complicate things.
- [X] ``gp.season['2017'].teams['Packers']`` - type team
    - will include plenty of info, such as ``name``, ``city``, ``logo``, ``abbr``
- [x] ``gp.season['2017'].teams['Packers'].games`` - type OrderedDict of game objects (similar to ``week.games``. Example: ``gp.season['2017'].teams['Packers'].games['reg']['Bears@Packers']`` -> game object
    - TODO: perhaps the ``game`` class should have a ``week`` property that points to the week object that the game belongs to.

## Other
- [X] ``gp.current['season']``
- [X] ``gp.current['week']``
- [X] ``gp.nfldate_to_datetime(nfldate_string)``
- [x] ``gp.subscription``

## Auth
- [X] ``gp.login(user, pass)``
- [x] ``gp.logout()``
- [X] ``gp.refresh_tokens()``

## Shows
- [x] ``gp.shows`` - type OrderedDict of shows
- [x] ``gp.shows['Hard Knocks'].seasons`` - type OrderedDict
- [ ] ``gp.shows['Hard Knocks'].seasons['2017']`` - type season
- [ ] ``gp.shows['Hard Knocks'].seasons['2017'].episodes`` - type list
- [ ] ``gp.shows['Hard Knocks'].seasons['2017'].episodes[0]``- type episode
- [ ] ``gp.shows['Hard Knocks'].seasons['2017'].episodes[0].streams``
- [ ] TODO: RedZone shows

## Broadcast
- [x] ``gp.broadcast['nfl_network'].desc``
- [x] ``gp.broadcast['nfl_network'].on_air``
- [x] ``gp.broadcast['nfl_network'].streams``
- [x] ``gp.broadcast['redzone'].desc``
- [x] ``gp.broadcast['redzone'].on_air``
- [x] ``gp.broadcast['redzone'].streams``

**Comment by jm-duke** [comment]
Closing this issue, as NFL has canceled the Gamepass service
