### ISSUE TITLE
Attach logging directly to requests session handle

### ISSUE THREAD

**Issue by aqw** [pigskin/pigskin#17]
Rather than using ``_log_request()``.

I'm not sure exactly how to do this yet, but it has to be possible somehow. Either some form of callback, or simply using requests/urllib3/httplib's logging support directly. What's blocking using httplib directly is that the response body cannot be logged. Or so I've read. I havn't looked into why.

**Comment by jm-duke** [comment]
Closing this issue, as NFL has canceled the Gamepass service
