### ISSUE TITLE
.raw() endpoint

### ISSUE THREAD

**Issue by aqw** [pigskin/pigskin#19]
A .raw() endpoint should be available on as many calls as possible, to expose the full server response.

I don't want pigskin to get in the business of normalizing and exposing every bit of information the services provide. It'll be unending, will break often, and the the different services may simply not provide all of the same info.

Having a .raw() call on objects would allow consumers of the API to get access to weird data they need without pigskin being on the hook for providing a stable API for it.

**Comment by jm-duke** [comment]
Closing this issue, as NFL has canceled the Gamepass service
