### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by aqw** [pigskin/pigskin#20]
Right now, most functions and properties will cause a request to the Game Pass service only once. This is optimal in some places, and completely counterproductive in other places.

I'm not sure what is the best approach to take here, but my thoughts are:

* should complete server responses be cached(see #19) and made available across functions/properties that would make the same request (``gp.seasons`` and ``gp.seasons['2017'].weeks`` for example)
* any caching should have a user configurable override (either to change the TTL, disable caching entirely, or perhaps get a fresh call just this one time)

TTL values should be sane and do what the user would expect.

* gp.seasons - TTL of forever
    - seasons info will change once a year
* gp.seasons['2017'].teams - TTL of forever
    - teams info will change once a year
* gp.seasons['2017'].weeks - TTL of forever
    - weeks info will change once a year
* gp.seasons['2017'].weeks['reg']['8'].games - TTL of forever if in the past (determined by current['season'] and current['week']; TTL of ??? minutes if the current season and week; TTL of forever (???) if in the future
    - this data is only expected to change if it's the current season/week.
* gp.season['2017']['reg'].week['8'].games['Bears@Packers'].versions - No caching (???)
* gp.season['2017']['reg'].week['8'].games['Bears@Packers'].versions['full'].streams - No caching

**Comment by jm-duke** [comment]
Closing this issue, as NFL has canceled the Gamepass service
