### ISSUE TITLE
Swap VCR cassettes according to which service is being tested

### ISSUE THREAD

**Issue by aqw** [pigskin/pigskin#21]
The end user experience when consuming the pigskin API should be the same regardless of which service (international or europe) that it's talking to. We should test that and enforce that. However, of course, those cassettes are completely different.

I havn't figured out exactly how I want to do this, but my current thoughts are:
* pass arguments to pytest ("all", "europe", "international", something like that) to declare which backends are being tested).
    - these can simply be stored in a variable, and the cassette names will be loaded accordingly (such as ``tests/cassettes/pigskin/europe_<test-name>.yaml``)
* tests for the user-facing API should be placed in the ``tests/`` folder.
* tests for the the peculiarities of a service should be in a service-specific subfolder such as ``tests/europe``.
    - cassettes can be stored in ``tests/cassettes/backends/europe/<test-file>_<test-name>.yaml``)

**Comment by jm-duke** [comment]
Closing this issue, as NFL has canceled the Gamepass service
