### ISSUE TITLE
Find the vcrpy equivalent of "allow_playback_repeats"

### ISSUE THREAD

**Issue by aqw** [pigskin/pigskin#22]
https://relishapp.com/vcr/vcr/docs/request-matching/playback-repeats

This would allow the invalid_responses.py tests and cassettes to be greatly simplified.

kevin1024/vcrpy#392

**Comment by dreki** [comment]
I would like to have this functionality as well. I would also like to be able to have requests happen in any order; right now, the order of interactions in a cassette file must match the order they happen in code, and I'd like to be able to decouple that.

**Comment by aqw** [comment]
It seems that upstream now has this feature: https://github.com/kevin1024/vcrpy/search?q=allow_playback_repeats

**Comment by jm-duke** [comment]
Oho, @aqw back in business? :grinning:

**Comment by jm-duke** [comment]
Closing this issue, as NFL has canceled the Gamepass service
