### ISSUE TITLE
errors on login from kodi/nflgamepass addon

### ISSUE THREAD

**Issue by erickj** [pigskin/pigskin#27]
Hi there!

I just installed the gamepass addon from the Kodi addon repository hoping to watch the superbowl next weekend on my new Kodi install, rather than on my phone :D

Unfortunately after I input my credentials I only get an error dialog that reads `failed_login` which led me to this repo.

I hacked the pigskin.py script to dump it's log file to disk and see the following (my username is redacted):

```
... request/response to v1/web/config omitted ...
[pigskin]: Debugging enabled.
[pigskin]: Python Version: 2.7.15 (default, Oct 15 2018, 15:24:06) 
[GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]
[pigskin]: Request URL: https://www.nflgamepass.com/api/user/oauth/token
[pigskin]: Method: post
[pigskin]: Payload: {'username': 'yyyyyy', 'password': 'xxxxxxxxxxxx', 'client_id': u'42cc360e-6fbb-4472-9437-2f088b8730de', 'grant_type': 'password'}
[pigskin]: Response code: 403
[pigskin]: Response: <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "http&#58;&#47;&#47;www&#46;nflgamepass&#46;com&#47;api&#47;user&#47;oauth&#47;token" on this server.<P>
Reference&#32;&#35;18&#46;3ff90a17&#46;1548284086&#46;6ce5bc69
</BODY>
</HTML>

[pigskin]: Login Failed.
[pigskin]: <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "http&#58;&#47;&#47;www&#46;nflgamepass&#46;com&#47;api&#47;user&#47;oauth&#47;token" on this server.<P>
Reference&#32;&#35;18&#46;3ff90a17&#46;1548284086&#46;6ce5bc69
</BODY>
</HTML>
```

Specifically the "you don't have permission" 403 error is the problem. I'm aware of the geolocated restriction of the service, and am physically located in Zurich, Switzerland. I generally have no problem using the web interfaces for game pass.

Any tips on how to debug this?

**Comment by jm-duke** [comment]
Closing this issue, as NFL has canceled the Gamepass service
